name: Build and deploy service

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: Target environment
        default: staging
        required: false
        options:
          - staging
          - orders

concurrency:
  group: ${{ github.event_name }}-${{ github.event.inputs.target_env }}-service
  cancel-in-progress: true

env:
  SERVICE_NAME: volume-tracker
  GITHUB_CICD_APP_APP_ID: 1061706

jobs:
  build-and-deploy-service:
    name: Build and deploy service
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Installation Token
        id: installation-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_CICD_APP_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Composite Actions Repository
        uses: actions/checkout@v2
        with:
          repository: paraswap/paraswap-github-actions
          ref: master
          token: ${{ steps.installation-token.outputs.token }}
          path: .github/paraswap-github-actions

      - name: Build and deploy service using composite action
        uses: ./.github/paraswap-github-actions/build-and-deploy-service
        with:
          service_name: ${{ env.SERVICE_NAME }}
          repository_sha: ${{ github.sha}}
          event_name: ${{ github.event_name }}
          authentication_token: ${{ secrets.AUTHENTICATION_KEY }}
          authorization_token: ${{ secrets.AUTHORIZATION_KEY }}
          data_center: ${{ secrets.DATA_CENTER }}
          target_env: ${{ github.event.inputs.target_env }}

      # We re-checkout composite actions repository due to a known bug that if composite action does its own checkout, it deletes any previous checkouts
      # thus, the post action fails on not finding the composite action we checked-out. See: https://github.com/actions/runner/issues/1300
      - name: ReCheckout Composite Actions Repository
        uses: actions/checkout@v2
        with:
          repository: paraswap/paraswap-github-actions
          ref: master
          token: ${{ steps.installation-token.outputs.token }}
          path: .github/paraswap-github-actions
